---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-test
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./tenants/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-prod
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./tenants/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
