---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: movy
  name: movy-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: movy
  name: movy
  namespace: movy-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: movy
  name: movy-reconciler
  namespace: movy-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: movy-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:movy-test:reconciler
- kind: ServiceAccount
  name: movy
  namespace: movy-test
