apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocky
  namespace: rocky-test
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - rocky.staging.tipzip.xyz
    secretName: rocky-staging-tls
  rules:
    - host: rocky.staging.tipzip.xyz # rocky.test.mybestdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
