---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: rocky
  name: rocky-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: rocky
  name: rocky
  namespace: rocky-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: rocky
  name: rocky-reconciler
  namespace: rocky-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rocky-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:rocky-test:reconciler
- kind: ServiceAccount
  name: rocky
  namespace: rocky-test
